name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Yarn
        run: npm install yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: extensions
          path: ./extension